## Configuration file to be used with `train.py` to create custom wake word/phrase models

# The name of the model (will be used when creating directoires and when saving the final .onnx and .tflite files)
model_name: "tammi_oi_20260319"

# The target word/phrase to be detected by the model. Adding multiple unique words/phrases will
# still only train a binary model detection model, but it will activate on any one of the provided words/phrases.
target_phrase:
  - tam_mi_oy
  - tam_mi_er

# Define the number of examples from each data file per batch. Note that the key names here
# must correspond to those define in the `feature_data_files` dictionary above (except for
# the `positive` and `adversarial_negative` keys, which are automatically defined). The sum
# of the values for each key define the total batch size for training. Initial testing indicates
# that batch sizes of 1024-4096 work well in practice.
batch_n_per_class:
  "ACAV100M_sample": 8192
  "adversarial_negative": 400
  "positive": 400
# Specific phrases that you do *not* want the model to activate on, outside of those generated automatically via phoneme overlap
# This can be a good way to reduce false positives if you notice that, in practice, certain words or phrases are problematic
custom_negative_phrases: []
# The location of pre-computed openwakeword features for false-positive validation data
# If you do not have deployment environment validation data, a good general purpose dataset with
# a reasonable mix with ~11 hours of speech, noise, and music is available here: https://huggingface.co/datasets/davidscripka/openwakeword_features
false_positive_validation_data_path: "./data/validation_set_features.npy"
# Paths to pre-computed openwakeword features for positive and negative data. Each file must be a saved
# .npy array (see the example notebook on manually training new models for details on how to create these).
# There is no limit on the number of files but training speed will decrease as more
# data will need to be read from disk for each additional file.
# Also, there is a custom dataloader that uses memory-mapping with loading data, so the total size
# of the files is not limited by the amount of available system memory (though this will result
# in decreased training throughput depending on the speed of the underlying storage device). A fast
# NVME SSD is recommended for optimal performance.
feature_data_files:
  "ACAV100M_sample": "./data/openwakeword_features_ACAV100M_2000_hrs_16bit.npy"
# The total number of positive samples to generate for training (minimum of 20,000 recommended, often 100,000+ is best)
# n_samples: 24938
# The total number of positive samples to generate for validation and early stopping of model training
# n_samples_val: 3734
# The maximum negative weight and target false positives per hour, used to control the auto training process
# The target false positive rate may not be achieved, and adjusting the maximum negative weight may be necessary
max_negative_weight: 2500
target_false_positives_per_hour: 0.5
target_accuracy: 0.8
target_recall: 0.7
# The batch size to use when performing data augmentation on generated clips prior to training
# It's recommended that this not be too large to ensure that there is enough variety in the augmentation
augmentation_batch_size: 8
# The number of times to apply augmentations to the generated training data
# Values greater than 1 reuse each generation that many times, producing overall unique
# clips for training due to the randomness intrinsic to the augmentation despite using
# the same original synthetic generation. Can be a useful way to increase model robustness
# without having to generate extremely large numbers of synthetic examples.
augmentation_rounds: 2
test_augmentation_rounds: 1
# The output directory for the generated synthetic clips, openwakeword features, and trained models
# Sub-directories will be automatically created for train and test clips for both positive and negative examples
output_dir: "../model"
checkpoint_save_path: "./model/checkpoints_cnn"
checkpoint_path: "./checkpoints"
# Define the type of size of the openwakeword model to train. Increasing the layer size
# may result in a more capable model, at the cost of decreased inference speed. The default
# value (32) seems to work well in practice for most wake words/phrases.
model_type: "cnn"
layer_size: 128
# The path to a fork of the piper-sample-generator repository for TTS (https://github.com/dscripka/piper-sample-generator)
piper_sample_generator_path: "./piper-sample-generator"
# The batch size to use with Piper TTS when generating synthetic training data
tts_batch_size: 50
# Define training parameters. The values below are recommended defaults for most applications,
# but unique deployment environments will likely require testing to determine which values
# are the most appropriate.
# The maximum number of steps to train the model
steps: 10000

# The directories containing Room Impulse Response recordings
rir_paths:
  - "./data/mit_rirs"
# The directories containing background audio files to mix with training data
noise_paths_train:
  music:
    - "./data/train/noise_train/music"
  speech:
    - "./data/train/noise_train/speech"
  noise:
    - "./data/train/noise_train/noise"

noise_paths_test:
  music:
    - "./data/test/noise_test/music_test"
  speech:
    - "./data/test/noise_test/speech_test"
  noise:
    - "./data/test/noise_test/noise_test"

save_debug_path_positive_test: "./augmented/20260319/"
save_debug_path_negative_test: "./augmented/20260319/"

positive_source: "./data/positive/"

positive_train_output_dir: "./train/clean_20251205/"
positive_test_output_dir: "./valid/clean_20251205/"
negative_train_output_dir: "./negative/train/similar_kt/"
negative_test_output_dir: "./negative/valid/similar_kt/"

box_positive_train_output_dir: "./negative/train/similar_kt/"
box_positive_test_output_dir: "./data/test/positive_test/20251110/stb/"
box_negative_train_output_dir: "./data/train/negative_train/20251110/stb/"
box_negative_test_output_dir: "./data/test/negative_test/20251110/stb/"

augmentation_probabilities:
  "Speed": 0.7
  "SevenBandParametricEQ": 0.25
  "TanhDistortion": 0.25
  "PitchShift": 0.25
  "BandStopFilter": 0.25
  "AddColoredNoise": 0.25
  "AddBackgroundNoise": 1
  "Gain": 1.0
  "RIR": 0.5

noise_type_probabilities:
  music: 0.2
  speech: 0.6
  noise: 0.2

noise_paths_duplicate_rate:
  music: 1
  speech: 1
  noise: 1

learning_rate: 0.0001